/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 * Shout out to https://icons8.com/icon/UkLBG0sZoWV0/add-male-user for the add male user icon. Icons8 home page https://icons8.com .
 * Shout out to https://icons8.com/icon/9485/borrow-book  for the borrow book icon. Icons8 home page https://icons8.com .
 * Shout out to https://icons8.com/icon/tsbJwZa5WChk/book-shelf  for the book shelf icon. Icons8 home page https://icons8.com .
 * Shout out to https://icons8.com/icon/gxuEDgFteZdP/database for the database icon. Icons8 home page https://icons8.com .
 * Shout out to https://icons8.com/icon/105085/graph-report for the graph report icon. Icons8 home page https://icons8.com .
 * Shout out to https://icons8.com/icon/12KiRC81sMRC/books for the books icon. Icons8 home page https://icons8.com .
 */
package Library_Management_System;

import Permissions_Roles_Package.PermissionsManager;
import Permissions_Roles_Package.User;

/**
 *
 * @author legac
 */
public class Library_Manager extends javax.swing.JFrame {
    
    private User currentUser;
    private PermissionsManager pm;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Library_Manager.class.getName());

    /**
     * Creates new form Library_Manager
     */
    public Library_Manager() {
        super("Library Manager");
        initComponents();
    }
    
    public Library_Manager(User authenticatedUser) {
        this.currentUser = authenticatedUser;
        pm = new PermissionsManager();
        super("Library Manager");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        New_User = new javax.swing.JButton();
        Lend_Items = new javax.swing.JButton();
        Inventory = new javax.swing.JButton();
        Collections = new javax.swing.JButton();
        Library_Reports = new javax.swing.JButton();
        Catalog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Manager");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 592, 110, -1));

        New_User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/icons8-add-user-100.png"))); // NOI18N
        New_User.setAlignmentX(0.5F);
        New_User.setAlignmentY(0.0F);
        New_User.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Manager", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 12))); // NOI18N
        New_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_UserActionPerformed(evt);
            }
        });
        getContentPane().add(New_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 122, -1, 124));

        Lend_Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/icons8-borrow-book-100.png"))); // NOI18N
        Lend_Items.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lend Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 12))); // NOI18N
        Lend_Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lend_ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(Lend_Items, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 122, -1, 124));

        Inventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/icons8-book-shelf-100.png"))); // NOI18N
        Inventory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 12))); // NOI18N
        Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryActionPerformed(evt);
            }
        });
        getContentPane().add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 122, -1, 124));

        Collections.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        Collections.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/icons8-database-100.png"))); // NOI18N
        Collections.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Collections", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 12))); // NOI18N
        Collections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CollectionsActionPerformed(evt);
            }
        });
        getContentPane().add(Collections, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 122, -1, 124));

        Library_Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/icons8-graph-report-100.png"))); // NOI18N
        Library_Reports.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Library Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 12))); // NOI18N
        Library_Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Library_ReportsActionPerformed(evt);
            }
        });
        getContentPane().add(Library_Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 122, 121, 124));

        Catalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/icons8-books-100.png"))); // NOI18N
        Catalog.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catalog", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 14))); // NOI18N
        Catalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogActionPerformed(evt);
            }
        });
        getContentPane().add(Catalog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 122, -1, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Library Management System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 30, 490, 62));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Library_Management_System/Images/plain-background-7102744_1920.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login_Page().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void New_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_UserActionPerformed
        // TODO add your handling code here:        
        setVisible(false);
        new New_User().setVisible(true);
    }//GEN-LAST:event_New_UserActionPerformed

    private void Lend_ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lend_ItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lend_ItemsActionPerformed

    private void InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InventoryActionPerformed

    private void CollectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CollectionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CollectionsActionPerformed

    private void Library_ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Library_ReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Library_ReportsActionPerformed

    private void CatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatalogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Library_Manager().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Catalog;
    private javax.swing.JButton Collections;
    private javax.swing.JButton Inventory;
    private javax.swing.JButton Lend_Items;
    private javax.swing.JButton Library_Reports;
    private javax.swing.JButton New_User;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
